CREATE TABLE CLIENTES (
    ID INT NOT NULL UNIQUE,
      NOME VARCHAR(50) NOT NULL,
      CPF VARCHAR(11) NOT NULL UNIQUE,
      TELEFONE VARCHAR(25) NOT NULL,
      PRIMARY KEY (ID)
);

CREATE TABLE ENDERECOS (
    ID int NOT NULL UNIQUE,
      CLIENTE_ID INT NOT NULL,
      LOGRADOURO VARCHAR(70) NOT NULL,
      NUMERO VARCHAR(20) NOT NULL,
      BAIRRO VARCHAR(25) NOT NULL,
      CIDADE VARCHAR(40) NOT NULL,
      ESTADO VARCHAR(40) NOT NULL,
      PRIMARY KEY (ID),
      FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)
);

CREATE TABLE VEICULOS (
    ID INT NOT NULL UNIQUE,
      PRECO DECIMAL(15,2) NOT NULL,
      PLACA VARCHAR(7) NOT NULL,
      MODELO VARCHAR(20) NOT NULL,
      MARCA VARCHAR(20) NOT NULL,
      ANO YEAR NOT NULL,
      PRIMARY KEY (ID)
);

CREATE TABLE PAGAMENTOS (
    ID INT NOT NULL UNIQUE,
      CLIENTE_ID INT NOT NULL,
      VEICULO_ID INT NOT NULL,
      PRECO DECIMAL(15,2) NOT NULL,
      DATA_PAGAMENTO DATE NOT NULL,
      PRIMARY KEY (ID),
      FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID),
      FOREIGN KEY (VEICULO_ID) REFERENCES VEICULOS(ID)
);